import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { SessionNavBar } from "@/features/sidebar/sidebar";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
   <body className="antialiased bg-background text-foreground">
    <ThemeProvider
     attribute="class"
     defaultTheme="system"
     enableSystem
     disableTransitionOnChange
    >
     <div className="min-h-screen flex flex-col md:flex-row">

      <aside className="hidden md:block border-r border-border">
       <SessionNavBar />
      </aside>


      <main className="flex-1 overflow-auto p-4 md:px-12 ml-2">
       {children}
      </main>
     </div>
    </ThemeProvider>
   </body>
  </html>
 );
}
