import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { SessionNavBar } from "@/features/sidebar/sidebar";
import { MenuBarDemo } from "@/features/bottombar/bottom-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased bg-background text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen flex flex-col md:flex-row overflow-hidden">
            <aside className="hidden md:block border-r border-border">
              <SessionNavBar />
            </aside>

            <main className="flex-1 overflow-auto md:px-12 ">
              {children}
            </main>
          </div>

          <div className="sticky bottom-3.5 z-50">
            <MenuBarDemo />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
